server:
  port: 8888

# server name
spring:
  application:
    name: configserver

  #git repo config
  cloud:
    config:
      server:
        git:
          default-label: config
          uri: https://github.com/wesleyweitianqi/config-server.git


